### ISSUE TITLE
The name gps conflicts with existing package

### ISSUE THREAD

**Issue by sundarjhu** [ICSM/pgmuvi#1]
Please rename gps.py to GPS.py or something else. There's an existing package called gps (https://pypi.org/project/gps/), and the command to import SpectralMixtureGPModel throws an ImportError.

Although it would be possible to add an extra path command and prepend the path to gps.py to the existing path, renaming the file requires less effort.

**Comment by pscicluna** [comment]
When using this as a package, the import will become
from pgmuvi.gps import ...
so I'm going to ignore the error and move test_script up a directory, forcing the future-proof import, instead.
________________________________
From: Sundar Srinivasan ***@***.***>
Sent: Friday, June 24, 2022 8:05:38 PM
To: ICSM/pgmuvi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ICSM/pgmuvi] The name gps conflicts with existing package (Issue #1)


Please rename gps.py to GPS.py or something else. There's an existing package called gps (https://pypi.org/project/gps/), and the command to import SpectralMixtureGPModel throws an ImportError.

Although it would be possible to add an extra path command and prepend the path to gps.py to the existing path, renaming the file requires less effort.

**Comment by pscicluna** [comment]
Now that test_script is deprecated and the new API is in place, this issue should have been closed a while ago.
