### ISSUE TITLE
Segmentation fault encountered

### ISSUE THREAD

**Issue by diegovasquez23** [ICSM/pgmuvi#26]
I encounter the following error when executing PGMUVI:
`  0%|                                                   | 0/300 [00:00<?, ?it/s]zsh: segmentation fault  python pgmuvi.py
(base) d.vasquez@192 pgmuvi % /Users/d.vasquez/opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
`

The same code executes without a segmentation fault on Colab, but this issue happens on my MacBook Pro.

Please help?

**Comment by sundarjhu** [comment]
@diegovasquez23 is able to run the code by downgrading to Python 3.9.12 from 3.9.13. @pscicluna, could you make this a requirement for installation for now? Thanks!

**Comment by pscicluna** [comment]
I will look in to adjusting out installation requirements. However, it would be very useful to know where multiprocessing is getting called from to narrow this down - @diegovasquez23 are you calling multiprocessing explicitly, or does this happen just in pgmuvi itself?

**Comment by diegovasquez23** [comment]
for the execution of PGMUVI with my light curves I do not use multiprocessing

**Comment by pscicluna** [comment]
3.9.13 has now been excluded in requires-python.
