### ISSUE TITLE
[Feature Request] Add lightcurve method to return a VOTable rather than save it to file

### ISSUE THREAD

**Issue by diegovasquez23** [ICSM/pgmuvi#38]
Would it be possible for the write_votable method to return an astropy table in addition to/instead of writing it to file?

**Comment by sundarjhu** [comment]
Perhaps a `to_table()` method?

**Comment by pscicluna** [comment]
With https://github.com/ICSM/pgmuvi/pull/42 merged, I am closing this issue. Please reopen if there's still more to do!
